// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// aum_interface
Rcpp::List aum_interface(const Rcpp::DataFrame err_df, const Rcpp::NumericVector pred_vec);
RcppExport SEXP _aum_aum_interface(SEXP err_dfSEXP, SEXP pred_vecSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::DataFrame >::type err_df(err_dfSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector >::type pred_vec(pred_vecSEXP);
    rcpp_result_gen = Rcpp::wrap(aum_interface(err_df, pred_vec));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_aum_aum_interface", (DL_FUNC) &_aum_aum_interface, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_aum(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
