// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// stl_sort
Rcpp::NumericVector stl_sort(Rcpp::NumericVector x);
RcppExport SEXP _aum_stl_sort(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(stl_sort(x));
    return rcpp_result_gen;
END_RCPP
}
// stl_set_insert
Rcpp::NumericVector stl_set_insert(Rcpp::NumericVector x);
RcppExport SEXP _aum_stl_set_insert(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(stl_set_insert(x));
    return rcpp_result_gen;
END_RCPP
}
// aum_map_interface
Rcpp::List aum_map_interface(const Rcpp::DataFrame err_df, const Rcpp::NumericVector pred_vec);
RcppExport SEXP _aum_aum_map_interface(SEXP err_dfSEXP, SEXP pred_vecSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::DataFrame >::type err_df(err_dfSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector >::type pred_vec(pred_vecSEXP);
    rcpp_result_gen = Rcpp::wrap(aum_map_interface(err_df, pred_vec));
    return rcpp_result_gen;
END_RCPP
}
// aum_sort_interface
Rcpp::List aum_sort_interface(const Rcpp::DataFrame err_df, const Rcpp::NumericVector pred_vec);
RcppExport SEXP _aum_aum_sort_interface(SEXP err_dfSEXP, SEXP pred_vecSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::DataFrame >::type err_df(err_dfSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector >::type pred_vec(pred_vecSEXP);
    rcpp_result_gen = Rcpp::wrap(aum_sort_interface(err_df, pred_vec));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_aum_stl_sort", (DL_FUNC) &_aum_stl_sort, 1},
    {"_aum_stl_set_insert", (DL_FUNC) &_aum_stl_set_insert, 1},
    {"_aum_aum_map_interface", (DL_FUNC) &_aum_aum_map_interface, 2},
    {"_aum_aum_sort_interface", (DL_FUNC) &_aum_aum_sort_interface, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_aum(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
