# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

aum_interface <- function(error_df, pred_vec) {
    .Call(`_aum_aum_interface`, error_df, pred_vec)
}

