# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

aum_sort_interface <- function(err_df, pred_vec) {
    .Call(`_aum_aum_sort_interface`, err_df, pred_vec)
}

aumLineSearch <- function(df, maxIterations) {
    .Call(`_aum_aumLineSearch`, df, maxIterations)
}

