# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

stl_sort <- function(x) {
    .Call(`_aum_stl_sort`, x)
}

stl_set_insert <- function(x) {
    .Call(`_aum_stl_set_insert`, x)
}

aum_map_interface <- function(err_df, pred_vec) {
    .Call(`_aum_aum_map_interface`, err_df, pred_vec)
}

aum_sort_interface <- function(err_df, pred_vec) {
    .Call(`_aum_aum_sort_interface`, err_df, pred_vec)
}

multithread <- function(err_df, pred_vec, threads) {
    invisible(.Call(`_aum_multithread`, err_df, pred_vec, threads))
}

